/*
 * Omarchy Dynamic GTK4 Theme Template for Nautilus
 * Automatically generated by Omarchy Quattro theme switcher
 */

/* 1. Dynamic Omarchy Variables */
@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};

@define-color view_bg_color {{ background }};
@define-color view_fg_color {{ foreground }};

@define-color headerbar_bg_color {{ background }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_border_color {{ color8 }};

/* Use GTK's shade() to dynamically lighten/darken panels relative to the background */
@define-color card_bg_color shade({{ background }}, 1.2);
@define-color card_fg_color {{ foreground }};
@define-color popover_bg_color shade({{ background }}, 1.2);
@define-color popover_fg_color {{ foreground }};

@define-color sidebar_bg_color shade({{ background }}, 0.85); 
@define-color sidebar_fg_color {{ foreground }};

@define-color accent_color {{ accent }};
@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ background }};

/* Status Colors */
@define-color destructive_color {{ red }};
@define-color destructive_bg_color {{ red }};
@define-color destructive_fg_color {{ background }};

@define-color success_color {{ green }};
@define-color success_bg_color {{ green }};
@define-color success_fg_color {{ background }};

@define-color warning_color {{ yellow }};
@define-color warning_bg_color {{ yellow }};
@define-color warning_fg_color {{ background }};

@define-color error_color {{ red }};
@define-color error_bg_color {{ red }};
@define-color error_fg_color {{ background }};


/* 2. Nautilus Specific Overrides */

/* Apply JetBrains Mono globally to Nautilus */
window.nautilus-window {
    font-family: "JetBrainsMono", "JetBrains Mono", monospace;
}

/* Target 83.33% font size to Main View */
window.nautilus-window,
window.nautilus-window base,
.nautilus-window notebook,
.nautilus-window view {
    background-color: @view_bg_color;
    color: @view_fg_color;
    font-size: 0.8333rem;
}

/* Target 83.33% font size to Top Bar */
window.nautilus-window headerbar {
    background-color: @headerbar_bg_color;
    color: @headerbar_fg_color;
    border-bottom: 1px solid @headerbar_border_color;
    box-shadow: none;
    font-size: 0.8333rem;
}

.nautilus-path-bar button {
    background-color: transparent;
    color: @window_fg_color;
    font-weight: bold;
}
.nautilus-path-bar button:hover {
    background-color: @card_bg_color;
    color: @accent_color;
}

/* Target 83.33% font size to Sidebar */
.nautilus-window placessidebar {
    background-color: @sidebar_bg_color;
    color: @sidebar_fg_color;
    font-size: 0.8333rem;
}
.nautilus-window placessidebar row:selected {
    background-color: alpha(@accent_bg_color, 0.15);
    color: @accent_color;
    font-weight: bold;
}
.nautilus-window placessidebar row:hover:not(:selected) {
    background-color: alpha(@headerbar_border_color, 0.2);
}

.nautilus-window flowboxchild:selected,
.nautilus-window treeview:selected {
    background-color: alpha(@accent_bg_color, 0.15);
    color: @window_fg_color;
    border-radius: 8px;
    outline: 2px solid @accent_bg_color;
}

rubberband, .rubberband {
    background-color: alpha(@accent_bg_color, 0.20);
    border: 1px solid @accent_bg_color;
    border-radius: 4px;
}

.nautilus-window button:not(.flat):not(.suggested-action):not(.destructive-action) {
    background-color: @card_bg_color;
    color: @window_fg_color;
    border: 1px solid @headerbar_border_color;
    border-radius: 6px;
}
.nautilus-window button:hover:not(.flat) {
    background-color: shade(@card_bg_color, 1.5); 
    color: @window_fg_color;
}
.nautilus-window button:checked,
.nautilus-window button:active {
    background-color: @accent_bg_color;
    color: @accent_fg_color;
}

.nautilus-window entry {
    background-color: @sidebar_bg_color;
    color: @window_fg_color;
    border: 1px solid @headerbar_border_color;
    border-radius: 6px;
}
.nautilus-window entry:focus {
    border-color: @accent_color;
    box-shadow: 0 0 0 2px alpha(@accent_color, 0.3);
}

scrollbar slider {
    background-color: @headerbar_border_color;
    border-radius: 10px;
}
scrollbar slider:hover,
scrollbar slider:active {
    background-color: @accent_color;
}